# Generated by Django 3.1.6 on 2021-03-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('building_number', models.IntegerField(verbose_name='# of building')),
                ('block', models.CharField(blank=True, max_length=10, null=True, verbose_name='Block')),
                ('entrance', models.IntegerField(blank=True, null=True, verbose_name='# of entrance')),
                ('appartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='# of appartment')),
                ('is_private_house', models.BooleanField(default=False, verbose_name='Private house')),
                ('is_billing_address', models.BooleanField(default=False, verbose_name='Billing address')),
                ('is_default_address', models.BooleanField(default=False, verbose_name='Default address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'db_table': 'user_address',
            },
        ),
    ]
