# Generated by Django 3.1.6 on 2021-03-09 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210309_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_billing_address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='zip_code',
            field=models.CharField(default='00000000000', max_length=10, verbose_name='ZIP Code'),
            preserve_default=False,
        ),
    ]
