# Generated by Django 3.1.6 on 2021-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210309_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='# of entrance'),
        ),
    ]
