# Generated by Django 3.1.6 on 2021-04-27 04:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210309_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/user_default.jpeg', upload_to=users.models.image_path, verbose_name='User Image'),
        ),
    ]
