# Generated by Django 3.1.6 on 2021-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
