# Generated by Django 3.1.6 on 2021-03-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210309_0617'),
        ('orders', '0002_orderitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='users.userprofile'),
        ),
    ]
